// ============================================================
//  ⚠ 자동 생성 파일 — 직접 수정하지 말 것.
//  scripts/transcribe.mjs 가 녹음을 전사해 만든 자막 비트.
//  원본 오디오: audio/261012.mp3
//  오디오 길이(초): 52.62
//  생성 시각: 2026-10-05T06:47:37.642Z
//  script.ts 에서:
//    import { generatedNarration, AUDIO_FILE, AUDIO_DURATION_SEC } from "./narration.generated";
// ============================================================
import type { NarrationBeat } from "../../types";

/** 영상에 삽입할 오디오 파일명 (public 기준 상대경로로 옮겨서 사용) */
export const AUDIO_FILE = "261012.mp3";
export const AUDIO_DURATION_SEC = 52.62;

export const generatedNarration: NarrationBeat[] = [
  { start: 0, text: "별거 아닌" },
  { start: 0.52, text: "줄 알았는데" },
  { start: 1.25, text: "엄청난 효과가" },
  { start: 1.98, text: "있었던 자세" },
  { start: 2.68, text: "단 10분만" },
  { start: 3.31, text: "누워있어도" },
  { start: 3.98, text: "피부가" },
  { start: 4.41, text: "좋아지고" },
  { start: 4.84, text: "스트레스까지" },
  { start: 5.51, text: "반토막" },
  { start: 5.83, text: "나는 자세가" },
  { start: 6.38, text: "있습니다" },
  { start: 6.88, text: "돈도 기구도" },
  { start: 7.55, text: "힘든 움직임도" },
  { start: 8.36, text: "필요가 없죠" },
  { start: 9.08, text: "바로 L자다리" },
  { start: 9.76, text: "자세인데요" },
  { start: 10.44, text: "대부분" },
  { start: 10.8, text: "모르는 놀라운" },
  { start: 11.52, text: "사실들이" },
  { start: 12, text: "있습니다" },
  { start: 12.52, text: "일단 피부와" },
  { start: 13.12, text: "얼굴이" },
  { start: 13.48, text: "좋아집니다" },
  { start: 14.12, text: "다리를 올리면" },
  { start: 14.91, text: "평소보다" },
  { start: 15.36, text: "많은 혈액과" },
  { start: 16, text: "산소가 얼굴로" },
  { start: 16.73, text: "올라갑니다" },
  { start: 17.4, text: "모세혈관이" },
  { start: 18.07, text: "산소공급을" },
  { start: 18.71, text: "받고 촉촉해지면서" },
  { start: 19.88, text: "칙칙하던" },
  { start: 20.38, text: "안색이 환해지고" },
  { start: 21.32, text: "피부에 윤기가" },
  { start: 22.14, text: "돌죠" },
  { start: 22.44, text: "그래서 서양에선" },
  { start: 23.33, text: "실제로" },
  { start: 23.68, text: "이걸 돈 안드는" },
  { start: 24.6, text: "안티에이징" },
  { start: 25.14, text: "자세라고" },
  { start: 25.58, text: "부릅니다" },
  { start: 26.08, text: "또한 다리를" },
  { start: 26.66, text: "심장보다" },
  { start: 27.12, text: "높이 올리면" },
  { start: 27.76, text: "코르티솔과" },
  { start: 28.31, text: "심박수가" },
  { start: 28.76, text: "눈에 띄게" },
  { start: 29.2, text: "하락하는데요" },
  { start: 30.04, text: "그래서 불안하고" },
  { start: 30.85, text: "잠 안올 때" },
  { start: 31.36, text: "딱 10분이면" },
  { start: 32.07, text: "잠이 잘 오고" },
  { start: 32.74, text: "마음도 편해지게" },
  { start: 33.49, text: "되죠" },
  { start: 33.76, text: "마지막으로" },
  { start: 34.33, text: "종이에 서있거나" },
  { start: 35.12, text: "앉아있느라" },
  { start: 35.72, text: "다리에 고여" },
  { start: 36.36, text: "붓게 만들던" },
  { start: 36.99, text: "피도" },
  { start: 37.32, text: "중력 덕분에" },
  { start: 37.96, text: "정맥을 타고" },
  { start: 38.64, text: "심장으로" },
  { start: 39.12, text: "쉽게 되돌아갑니다" },
  { start: 40.08, text: "그 덕에 붓기랑" },
  { start: 41, text: "묵직한 피로까지" },
  { start: 42, text: "눈녹듯 사라지죠" },
  { start: 42.92, text: "결국 피부," },
  { start: 43.5, text: "스트레스," },
  { start: 44.08, text: "숙면, 혈액순환까지" },
  { start: 45.31, text: "한 번에 잡는" },
  { start: 45.92, text: "겁니다" },
  { start: 46.36, text: "방법은 어이없을" },
  { start: 47.27, text: "만큼 쉬운데" },
  { start: 47.96, text: "벽이든 침대든" },
  { start: 48.76, text: "엉덩이 붙이고" },
  { start: 49.6, text: "다리 쭉 올려서" },
  { start: 50.54, text: "10분만 눈" },
  { start: 51.06, text: "감고" },
  { start: 51.28, text: "있으면 끝입니다" },
];
